name: http-double-compression

services:
  webserver:
    image: node:24-alpine
    ports:
      - 80:8080/tcp
    command: node /opt/http-double-compression/index.js
    restart: unless-stopped
    volumes:
      - "./index.js:/opt/http-double-compression/index.js:ro"
